### ISSUE TITLE
[Feature] escape control

### ISSUE THREAD

**Issue by ivan1986** [FriendsOfSymfony/FOSJsRoutingBundle#101]
Add option or other function whis not escape values in url.

AngularJS ngResource use :name parameters and ":" escape before enter lib. 

For example now for AngularJS i use this hack

```
Routing.genTpl = function(name, opt_params, absolute) {
    return Routing.generate(name, opt_params, absolute).replace(/%3A/g,':')
};

return $resource(Routing.genTpl('posts', { "user": ':user' }), {}, {
            'get': {method:'GET', isArray:true}
        });

```

Any other js library, works whis paremeters in urls - [] {} and other symbols.

**Comment by orlandothoeny** [comment]
Would be nice for React Js + React Router too. It uses the same ":parameter" syntax.

**Comment by stof** [comment]
Does not make sense. This bundle is not about doing client-side routing, but about generating URLs your Symfony routes in the client side.
