### ISSUE TITLE
the router.js code is not "strict mode" compatible

### ISSUE THREAD

**Issue by pjordaan** [FriendsOfSymfony/FOSJsRoutingBundle#118]
in our project we merge all our javascript in a big closure and use "use strict" since strict mode prevents us from falling in one of the many traps of many javascript quirks.

We want to incorporate the routing of symfony 2 in our application, but it seems router.js is not strict mode compatible for the simple fact router.js tries to do 
var k= this; to get the window object. This fails in strict mode, since this is null in strict mode. Looking at the rest of the code, the rest should work just fine in strict mode.

**Comment by brayansdt** [comment]
Why not k = window?
since "this" in this scope means "window".

**Comment by pjordaan** [comment]
@brayansdt this is not the case in strict mode.
 But right now I think it can't be fixed, unless you do some nasty string replace afterwards or switch to a different compiler. For my personal code I did the nasty string replace thing afterwards.

**Comment by michaelperrin** [comment]
Can I find somewhere the non-minified `router.js` file so that it can be easily debugged? It's a real issue that FOSJsRoutingBundle can't work in strict mode, so I'd like to have a look into it to solve the problem.

**Comment by willdurand** [comment]
@michaelperrin please see: https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/blob/master/Resources/js/router.js.
