### ISSUE TITLE
undefined protocol and domain in routing output

### ISSUE THREAD

**Issue by fabianbartsch** [FriendsOfSymfony/FOSJsRoutingBundle#135]
Hey guys!

I have the following problem, and no clue how to solve it:

My controller annotation:

@Method("GET")
@Route("/search/{searchterm}", name="_api_player_search", options={"expose"=true})

My JavaScript:

console.log(Routing.generate('_api_player_search', {searchterm: 'aaron', limit: 5}, true));

The output in firebug console:

undefined://undefinedundefined/api/player/search/aaron?limit=5

Testing on a local xampp server, Symfony v 2.4.2, FOSJsRoutingBundle in is actual version from 18. Feb 2014.

**Comment by armancho7777777** [comment]
Got the same problem (undefined host) - is there a fix underway or workaround present?

**Comment by fidovo** [comment]
Got same problem, undefined schema, any solution?

**Comment by armancho7777777** [comment]
Yes.

**Comment by fidovo** [comment]
How can i solve it please? :)

**Comment by willdurand** [comment]
Can you try version 1.6.2 of this bundle?

**Comment by armancho7777777** [comment]
My composer:

"require": {
       ...
       "friendsofsymfony/jsrouting-bundle": "^1.6",
       ...
}

**Comment by armancho7777777** [comment]
Yes, it helped.
Thank you.

**Comment by allfreelancers** [comment]
I use FOSrouting 1.6.2 and I have same problem
