### ISSUE TITLE
The route "toto" does not exist. 

### ISSUE THREAD

**Issue by sanchobouillant** [FriendsOfSymfony/FOSJsRoutingBundle#136]
Hi,

I use FOSJsRouting at some places in my project, it work well, except for one page.

I have in my console log: The route "toto" does not exist. 

my View:
```JavaScript<script>
function myFunction(localeVar)
{
    var test = Routing.generate('toto', {myParam: localeVar});
}
</script>

<a href="#" onclick="myFunction('...')">myLink</a> 
```

My controller:
```php
    /**
     *
     * @Route("/mysuperurl/{myParam}", name="toto", options={"expose"=true})
     *
     */
    public function totoAction($myParam)
    {
        return new Response();
    }
```
```bash
php app/console fos:js-routing:debug | grep toto
toto                             ANY      ANY    ANY  /mysuperurl/{myParam}
```

I use the version @stable.

Some ideas ?

**Comment by molchanoviv** [comment]
I also faced this bug. Router doesn't add finishing slash when optional parameter is absent.

**Comment by molchanoviv** [comment]
I also faced similar issue. Router adds redundant slash when optional parameter is absent.

**Comment by razmo** [comment]
Have also the same issue. It work fine en dev mode but not in prod. 
I have correctly added the bundle routes as described in documentation with :
```
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
```
But when i load the page i can see in firebug that the route ```fos_js_routing_js``` can not be found.
```https://local.my_project.com/js/routing : 404 Not found```

**Comment by rmed19** [comment]
I had the same issue, I missed to add :

<script src="{{ path('fos_js_routing_js', {'callback': 'fos.Router.setData'}) }}"></script>

**Comment by kpicaza** [comment]
I had the same issue, and after comparing with the routes that works properly, I found the missing parameters defining the route. example:

```
route_name:
    path: /pathto/route
    defaults: { _controller: CONTROLLER_METHOD}
    # missing options == Routing.generate() function can't find "route_name" route
    options:
        expose: true
```

I hope this helps someone.
Sorry for my English
