### ISSUE TITLE
[DX] Generate relative/absolute URLs using the same method names as Symfony

### ISSUE THREAD

**Issue by javiereguiluz** [FriendsOfSymfony/FOSJsRoutingBundle#154]
When reading the [Generating URIs](https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/blob/master/Resources/doc/index.md#generating-uris) section of the documentation, I wondered why there is a single `Routing.generate()` method instead of mimicking the methods provided by Symfony:

```js
// original method
Routing.generate('my_route', { id: 10 });

// proposal
Routing.path('my_route', { id: 10 });

// - - - - -

// original method
Routing.generate('my_route', { id: 10 }, true);

// proposal
Routing.url('my_route', { id: 10 });
```

So basically my proposal is to use `path()` and `url()` methods to simplify the use of this bundle to developers already used to Symfony.

**Comment by willdurand** [comment]
I do agree with @dincho.
