### ISSUE TITLE
Grouping exposed routes

### ISSUE THREAD

**Issue by TroodoNmike** [FriendsOfSymfony/FOSJsRoutingBundle#174]
Would it be possible and not too hard to implement grouping exposed routes?

I have a backend cms exposed routes collection (which I use on the backend) and I would want separate routes collection on the frontend (which does not show exposed routes from backend).

What do you think? Is there other way?

**Comment by ConneXNL** [comment]
Seems like a lot of people face this problem, inc. me.
https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/pull/108

**Comment by luishdez** [comment]
+1 I've the same problem. Groups like validation or serialization would be awesome
