### ISSUE TITLE
can this be moved to PSR4?

### ISSUE THREAD

**Issue by cordoval** [FriendsOfSymfony/FOSJsRoutingBundle#176]
just wondering if this can be moved to PSR4?

**Comment by willdurand** [comment]
How useful would it be?

**Comment by cordoval** [comment]
it is useful to avoid going down many levels to do a git commit or etc. Mostly for development and welcoming more PRs.

**Comment by cordoval** [comment]
i will just do it right? cc @willdurand

**Comment by stof** [comment]
the main reason to switch to PSR-4 is to stop relying on the target-dir in Composer, which is a deprecated feature (it was introduced to emulate *some* PSR-4 use cases with PSR-0 only). Several other FOS bundles have already been updated. So yeah, I suggest you to send a PR changing the composer.json

**Comment by willdurand** [comment]
sure :)

**Comment by cordoval** [comment]
achieved in #178
