### ISSUE TITLE
Encoding generated routings

### ISSUE THREAD

**Issue by colejarczyk** [FriendsOfSymfony/FOSJsRoutingBundle#177]
I don't know it is good or bad, but it's definitely confusing.

```javascript
angularModuleService.factory('AngularModule', ['$resource',
    function ($resource) {
        return $resource(
            Routing.generate("symfony_routing_name", {_format: 'json', param1: ':param1', param2: ':param2'}),
            {param1:"@param1", param2: "@param2"});
    }
]);
```

 I'm using this code, but parameters are not passed to url, because colons are encoded. I know it's good for URLs, but it is bad when you use angularjs. To pass parameters to URL I must decode URL. 
```javascript
decodeURIComponent(Routing.generate("symfony_routing_name", {_format: 'json', param1: ':param1', param2: ':param2'}))
```

Should this work like this?

**Comment by stof** [comment]
the router is generating an url, not a single uri component

**Comment by colejarczyk** [comment]
What do you think about adding method to generate URI? Router.generateURI() sounds good to me, but I don't know if it is useful for anyone else?
