### ISSUE TITLE
Including js files in php

### ISSUE THREAD

**Issue by jpintor14** [FriendsOfSymfony/FOSJsRoutingBundle#179]
I'm trying to include the js files in php.
The documentation explains this  two lines in Twig:

```
<script src="{{ asset('bundles/fosjsrouting/js/router.js') }}"></script>
<script src="{{ path('fos_js_routing_js', {"callback": "fos.Router.setData"}) }}"></script>
```

But, how I write this in php? 
I added the router.js file:
```
<script src="/js/router.js"></script>
```
Executed the command:
```
php app/console fos:js-routing:dump
```
Finally, included the generated js file:
```
<script src="/js/fos_js_routes.js"></script>
```
The console says:
```
Uncaught ReferenceError: goog is not defined
Uncaught ReferenceError: fos is not defined
```

Any idea about the error?

Thanks a lot for your time!

**Comment by stof** [comment]
Why do you mean by "in PHP" ?

**Comment by jpintor14** [comment]
Sorry, I mean that not use Twig, I use php.
So, i can't include the js files like in the documentation example.

```
<script src="{{ asset('bundles/fosjsrouting/js/router.js') }}"></script>
<script src="{{ path('fos_js_routing_js', {"callback": "fos.Router.setData"}) }}"></script>
```

Thanks again.

**Comment by stof** [comment]
Well, if you use PHP templates, use the ``path()`` and ``asset()`` equivalents for PHP templates: http://symfony.com/doc/current/book/templating.html#linking-to-pages and http://symfony.com/doc/current/book/templating.html#linking-to-assets

**Comment by jpintor14** [comment]
Ok,but the problem is when I use js functions like this (AJAX request for example):

```
var url = "../second_file.php"
$("#example").load(url);
```

How I build my url?

**Comment by stof** [comment]
Well, these asset helpers are precisely about building these URLs

**Comment by jpintor14** [comment]
Ok, the only way I found is save the url in an input hidden.
So, I looked for FOSJsRoutingBundle to expedite the process.

The issue I want is to access the route from the js file, To replace "url"

```
var url = "../second_file.php"
$("#example").load(url);
```

Maybe I didn't explain well.

**Comment by dcarbone** [comment]
I am slightly confused by this question.  Are you asking how to generate a URL to an asset or a specific PHP file?

**Comment by jpintor14** [comment]
I am asking how to generate URL to call an action of one Controller in javascript.
I use PHP, no Twig, to include the js files.

For example, call to my_proyect/items .

Thanks again for your time!

**Comment by stof** [comment]
Well, I gave you the link to the Symfony documentation about generating asset paths and route URLs in templates, and these documentation show both the Twig and PHP examples.

then, once you have loaded the FOSJsRoutingBundle javascript in your page, the way to generate URLs for routes in the Javascript does not change when you don't use Twig, given that it happens client side anyway. It is ``Routing.generate('my_route_to_expose', { id: 10 });``, as described in the doc of the bundle

**Comment by jpintor14** [comment]
Ok, this is my problem, I included the two js files:

```
<script src="/js/router.js"></script>
<script src="/js/fos_js_routes.js"></script>
```

But the console says:

```
Uncaught ReferenceError: goog is not defined
Uncaught ReferenceError: fos is not defined
```
I don't know what is wrong.

**Comment by stof** [comment]
The router.js file is **not** at the path ``/js/router.js``. If you look at your console, you will see that you have a 404 for this asset before the reference errors. this is why I linked you to the doc about referencing assets in templates

**Comment by jpintor14** [comment]
No, I copied the file in the path /js.
The error says "Uncaught ReferenceError", no 404

Thanks a lot for your answer.

**Comment by dcarbone** [comment]
Does the below work?
```php
<script src="<?php echo $view['assets']->getUrl('bundles/fosjsrouting/js/router.js'); ?>"></script>
<script src="<?php echo $view['router']->generate('fos_js_routing_js', array('callback' => 'fos.Router.setData')); ?>"></script>
```

I have yet to attempt writing Symfony2 templates in PHP (twig is great), but judging by the docs and what you appear to wish to do I think this should be pretty close.

Do you understand why your code was not working?  As the documentation states, you need to generate two separate TYPES of urls.  One is a raw url to an asset file (`router.js`), the other is a url based upon a route definition (`fos_js_routing_js`).  It is NOT "fos_js_routing_js.js".

If you look here: https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/blob/master/Resources/config/routing/routing.xml

You will see that `fos_js_routing_js` references the controller: https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/blob/master/Controller/Controller.php where lots of magic happens.


One cannot simple "include" a route as a js file.

**Comment by jpintor14** [comment]
Great! This way I solved my problem.

Thanks a lot for your help!!!



The only thing is that the variables not build in "Symfony sintax".

I mean, I use

```
var url= Routing.generate('items', { id: 10 });
```
The result:
````
project/items?id=10
```
What I want:
```
project/items/10
```

This is no serious, I can concatenate the var to the url generated:
```
var url = Routing.generate('items');
urk += "/" + page;
```

**Comment by dcarbone** [comment]
In that case you should specify "id" as a parameter for your route.

Go (here)[http://symfony.com/doc/current/book/routing.html] (http://symfony.com/doc/current/book/routing.html) and then look at the section titled *Routing with Placeholders*

**Comment by jpintor14** [comment]
OK, you're right!
I was passing wrong the variable.

Thanks again from Spain! Greetings!
