### ISSUE TITLE
Error: Class 'JsonpCallbackValidator' not found in Controller.php of jsRoutingBundle on line 110

### ISSUE THREAD

**Issue by falexis77** [FriendsOfSymfony/FOSJsRoutingBundle#186]
Hi,

I have problem with the bundle.
I use Ajax to change id on the URL. But, when i click, my path is not found.
So I make the command  fos:js -routing:debug , my path is taken into account.
I looking for the problem and maybe the problem may come of "callback=fos.Router.setData" .
When, i open firebug and see on the "callback=fos.Router.setData" file, i have this error about JsonpCallbackValidator.
Thanks

**Comment by stof** [comment]
Are you installing the bundle through Composer or through a different way ?

**Comment by falexis77** [comment]
I'm cannot install with Composer due to network restrictions of company
So ,i'm install manually but i take JsonpCallbackValidator of Will Durand with FOSjsRouting

**Comment by stof** [comment]
have you configured the autoloading for the JsonpCallbackValidator package properly when installing it manually ?

**Comment by falexis77** [comment]
Ok,I made a success to configure JsonpCallbackValidator, it works, a error with autoloading, actually.
Sorry about that, i'm use it for the first time
I'm use  : Routing.generate('my_route_to_expose', { id: 10 });, to change url when we click on a button on Ajax. 
We must to use window.location to displays informations according to id?
