### ISSUE TITLE
Feature request: Add method to check for route existence

### ISSUE THREAD

**Issue by IwfY** [FriendsOfSymfony/FOSJsRoutingBundle#189]
Sometimes I'd like to check if a route exists and is available.

Generating or getting a route that does not exist throws an error. It would be nice if I could check beforehand if some route actually exists.

Routing.getRoutes() returns a goog object that is not easily accessible without including additional dependencies.

I'm using the following ugly workaround:

    if ('routeName' in Routing.getRoutes().c) {
        [...]
    }

**Comment by raziel057** [comment]
See the PR here #161

**Comment by stof** [comment]
@raziel057 #161 is not about this at all

**Comment by raziel057** [comment]
@stof Exact match can be used to check the existance of an URL and not a route name. Sorry

**Comment by willdurand** [comment]
Because of lack of interest/time for maintaining this project, I am not accepting feature requests anymore, yet I do accept pull requests and I am willing to discuss/iterate over them.
