### ISSUE TITLE
where is your version number listed?

### ISSUE THREAD

**Issue by wolfdogg** [FriendsOfSymfony/FOSJsRoutingBundle#191]
How do i find your version number, if i want to use composer by version number manyall, instead of using composer require which would need me to reverse teh normal flow of which way i put my files.  i.e. i like to upload my composer.json, not make automatic edits to it, then downlaod it. 

right now i have `"friendsofsymfony/jsrouting-bundle": "~1.5",` but im trying to find out if there is a new version, so i can get my composer.json all up to date..

**Comment by merk** [comment]
You can find versions of a package for use in composer on packagist.org.

https://packagist.org/packages/friendsofsymfony/jsrouting-bundle
