### ISSUE TITLE
Class constants in annotations

### ISSUE THREAD

**Issue by Tocacar** [FriendsOfSymfony/FOSJsRoutingBundle#194]
It would be really great if FOSJsRoutingBundle supported the use of class constants in annotations (for instance as 'default' or 'requirements' options). 

For me at the moment, class constant declarations are copied to the dumped fos_js_routes.js as literal strings, instead of the constant value itself.

**Comment by stof** [comment]
FOSJsRoutingBundle does not parse class annotations itself at all. So it supports anything supported by the the annotation parser.
Actually, this bundle does not perform any route parsing. It just gets the result of the Symfony parsing.

**Comment by Tocacar** [comment]
@stof  It is possible to use class constants in annotations though.  Just not if you're going to be exposing them through FOSJsRouting.  It would be nice if this was possible.
