### ISSUE TITLE
forbidden

### ISSUE THREAD

**Issue by Falar81** [FriendsOfSymfony/FOSJsRoutingBundle#195]
hi,

i have this problem:

i have generate this url:
<code>
window.open (Routing.generate('anagrafica_etichette_pdf',{ids: ids}),'_blank',false); //ids is very long.
</code>
in my controller:
<code>

    /**
     * Print Anagrafica PDF.
     *

     * @Route("/anagraficaEtichettePdf/{ids}", name="anagrafica_etichette_pdf", options={"expose"=true})
    * @Method("POST")
     */

    public function anagraficaEtichettePdfAction($ids){
    
        $em = $this->getDoctrine()->getManager();
        $query = $em->createQuery('SELECT a
    FROM KritekGestionaleBundle:Anagrafica a WHERE a.id IN ('.$ids.')');
    
        $html = $this->renderView('KritekGestionaleBundle:Anagrafica:anagraficaEtichettePdf.html.twig', array('anagraficheList'=>$query->getResult()));

        return new Response(
            $this->get('knp_snappy.pdf')->getOutputFromHtml($html),
            200,
            array(
                'Content-Type'          => 'application/pdf',
                'charset' => 'UTF-8',
            )
        );
    }
</code>

result is:
Forbidden

You don't have permission to access /app_dev.php/anagrafica/anagraficaEtichettePdf/00006,00007,00008,00009,00010,00011,00012,00013,00014,00015,00016,00017,00018,00019,00020,00021,00022,00023,00024,00025,00026,00027,00028,00029,00030,00031,00032,00033,00034,00035,00036,00037,00038,00039,00040,00041,00042,00043,00044,00045,00046,00047,00048,00049,00050,00051,00052,00053,00054,00055,00056,00057,00058,00059,00060,00061,00062,.......(over 4000).
the re

request method is get but should be post

**Comment by stof** [comment]
``window.open`` will never perform a POST request. It is not possible to open a new window through a POST request in browsers.

this has nothing to do with FOSJsRoutingBundle (which only generates the URL and does not deal with making requests)
