### ISSUE TITLE
DEPRECATED

### ISSUE THREAD

**Issue by tubssp** [FriendsOfSymfony/FOSJsRoutingBundle#196]
DEPRECATED - The "pattern" option in file "/symfony/vendor/friendsofsymfony/jsrouting-bundle/Resources/config/routing/routing.xml" is deprecated since version 2.2 and will be removed in 3.0. Use the "path" option in the route definition instead. -

    Called from XmlFileLoader::parseRoute() at line 85
    Called from XmlFileLoader::parseNode() at line 61
    Called from XmlFileLoader::load() at line 107
    Called from FileLoader::import() at line 157
    Called from YamlFileLoader::parseImport() at line 93
    Called from YamlFileLoader::load() at line 107
    Called from FileLoader::import() at line 157
    Called from YamlFileLoader::parseImport() at line 93
    Called from YamlFileLoader::load() at line 107
    Called from FileLoader::import() at line 157
    Called from YamlFileLoader::parseImport() at line 93
    Called from YamlFileLoader::load() at line 107
    Called from FileLoader::import() at line 157
    Called from YamlFileLoader::parseImport() at line 93
    Called from YamlFileLoader::load() at line 45
    Called from DelegatingLoader::load() at line 76
    Called from DelegatingLoader::load() at line 54
    Called from Router::getRouteCollection() at line 373
    Called from Router::getMatcherDumperInstance() at line 288
    Called from Router::Symfony\Component\Routing\{closure}()
    Called from call_user_func() at line 46
    Called from ConfigCacheFactory::cache() at line 302
    Called from Router::getMatcher() at line 250
    Called from Router::matchRequest() at line 137
    Called from RouterListener::onKernelRequest()
    Called from call_user_func() at line 61
    Called from WrappedListener::__invoke()
    Called from call_user_func() at line 164
    Called from EventDispatcher::doDispatch() at line 53
    Called from EventDispatcher::dispatch() at line 167
    Called from ContainerAwareEventDispatcher::dispatch() at line 124
    Called from TraceableEventDispatcher::dispatch() at line 3083
    Called from HttpKernel::handleRaw() at line 3056
    Called from HttpKernel::handle() at line 3207
    Called from ContainerAwareHttpKernel::handle() at line 2429
    Called from Kernel::handle() at line 30

**Comment by TurkeyFried** [comment]
It was fixed in April, but has not been included in a release yet.
https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/commit/633f56e9f50422df03567c256e7e72c8f0585c68

**Comment by stof** [comment]
@tubssp before opening issues on all bundles you use, it would be great to try their dev versions (or check the history of changes after the latest release) to see whether it has already been fixed or no

**Comment by Padam87** [comment]
Could you please add a new tag?

**Comment by tubssp** [comment]
@stof Sorry.

**Comment by stof** [comment]
I need to have a deeper look at this. Deprecations have been fixed in the master branch, which is not yet ready for a 2.0 release. I need to check whether it can be backported to 1.x without too much hassle.

**Comment by tgabi333** [comment]
+1 for a new 1.x release

**Comment by trappar** [comment]
+1 for whatever gets this fixed sooner than later

**Comment by althaus** [comment]
Any news on this, @stof ?

**Comment by benr77** [comment]
+1 for backporting - looks basically like a search & replace of pattern -> path. Please tag new release soon. Thanks!

**Comment by althaus** [comment]
So... Symfony 3 is at the horizon and no update available. :disappointed:

**Comment by MECU** [comment]
Symfony 3.0 is now released. This now prevents upgrading.

**Comment by frandieguez** [comment]
+1

**Comment by behramcelen** [comment]
:+1: for backporting

**Comment by dextervip** [comment]
+1 for backporting

**Comment by thundo** [comment]
+1

**Comment by willdurand** [comment]
We need a few more +1 to enable this special hidden GitHub feature that backports the fix automatically. Go go go!!!

Or maybe one of you will try to contribute to this open source project..

**Comment by MECU** [comment]
Or maybe there already is a fix and only the owners can push/merge/solve the problem.

https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/issues/196#issuecomment-107558229

**Comment by willdurand** [comment]
There is no fix for 1.x, period. Please either wait a bit or contribute to the right version.

**Comment by willdurand** [comment]
Update: version 1.x should be fixed around mid-January.

**Comment by willdurand** [comment]
Hi there! Could you please try version [1.6.0](https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/releases/tag/1.6.0)? Thank you.

**Comment by althaus** [comment]
@willdurand Seems to work fine. Deprecation warning vanished. :tada:
