### ISSUE TITLE
Non-existent service "fos_js_routing.extractor" error

### ISSUE THREAD

**Issue by alsar** [FriendsOfSymfony/FOSJsRoutingBundle#199]
I installed the bundle and I get an error when I try to run `fos:js-routing:dump` command (or debug) from the console.

I get: `[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]  
  You have requested a non-existent service "fos_js_routing.extractor". `

I'm using Symfony 2.7.1. I enabled the bundle and added it to the routing.

**Comment by stof** [comment]
Are you running your command in the prod env or the dev env ? If it is in the prod env, take care to clear your cache

**Comment by alsar** [comment]
In the dev environment.

**Comment by alsar** [comment]
Reinstalled the bundle and now it works. Strange.
