### ISSUE TITLE
How to use FOSJsRoutingBundle

### ISSUE THREAD

**Issue by Ziiweb** [FriendsOfSymfony/FOSJsRoutingBundle#200]
Hi,

I have installed FOSJsroutingBundle as the instructions say, and I have added the line below to to a .js file I'm including in the same time inside a .html.twig file.

`{{ path(my_route) }}`

So I get this javascript error around that line: SyntaxError: invalid property id

Any help? Im doint it in the right way? is it just adding `{{ path(my_route) }}` to my .js file?

**Comment by stof** [comment]
Adding some Twig syntax in your JS files is absolutely not the goal of this bundle (it simply cannot work).
Have you read the documentation of the bundle ? https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/blob/master/Resources/doc/index.md
