### ISSUE TITLE
How to restrict request with only 'callback' parameter?

### ISSUE THREAD

**Issue by chellem** [FriendsOfSymfony/FOSJsRoutingBundle#207]
Hello,

When I make a request without the 'callback' query string or with a different query string, I get all exposed routes with the requirements and everything.  I believe this is intentional but I considered as a security risk.  Is it possible from the config to limit it only to the 'callback' query string?

Regards,
Chellem

**Comment by willdurand** [comment]
I don't think it is possible by now.

**Comment by stof** [comment]
Well, when you pass the callback, you get exactly the same info, but in JSON rather than JSON.
If you consider exposing your routing a security risk, don't use the JsRoutingBundle at all, as its *only* feature is to expose this info to the client-side code.
