### ISSUE TITLE
Prefix not generated in Route

### ISSUE THREAD

**Issue by AlexJunge** [FriendsOfSymfony/FOSJsRoutingBundle#209]
Hey,

I am trying to use the FOSJsRoutingBundle in my Project but I am having a problem with the prefix. 

I use a language prefix througout my application defined in the routing.yml and when i try to call the `Routing.generate("my_link");` I get the console message 

```
Uncaught Error: The route "device_summary" requires the parameter "_locale".
(anonymous function) @ 588ef3b_part_4.js:10
m.forEach.d @ 588ef3b_part_4.js:7
i.m @ 588ef3b_part_4.js:10
(anonymous function) @ summary.js:11
m.event.dispatch @ 588ef3b_part_1.js:4
m.event.add.r.handle @ 588ef3b_part_1.js:4
```

My routing.yml is built up like this:

```
app:
    resource: "@myBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: |de|en

....

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
```

is there a solution to this?

Thank you.

**Comment by merdocif** [comment]
just add to your
 ```javascript
 var locale= {{ app.request.locale }} ;
Routing.generate("my_link",{'_locale':locale});
```

should work

**Comment by AlexJunge** [comment]
Thanks! Works :+1:

**Comment by stof** [comment]
yeah. symfony is able to inject the _locale placeholder automatically, but our JS generator cannot
