### ISSUE TITLE
Dumping routers when database is not available

### ISSUE THREAD

**Issue by zajca** [FriendsOfSymfony/FOSJsRoutingBundle#211]
I'm dumping routes and building application on build server where database is not available.

I have updated composer.json to run just, buildParameters and buidlBootstrap.

But I'm using gulp to concat all JS files including routes. But when I run: ```console fos:js-routing:dump --env=prod --no-debug``` I end up with ```ConnectionException``` because database is not available. It's possible to dump routes without connecting to database?

**Comment by stof** [comment]
FOSJsRoutingBundle does not rely on any database (unless you use a custom router relying on the database).

Please provide a stack trace of the exception by running the command in verbose mode

**Comment by zajca** [comment]
I take deeper look and it's bit confusing. This occurs only when cache is not warmed up but it acts like this:
When I run cache warm up when there is no cache task will fail because of database connection but when I run it second time it will run just fine without error.

Same is with routing dump (or any other command which will warmup cache), first it will fail but second run it will pass.

This is not problem of FOSJsRoutingBundle, but looks like problem in symfony or my config :D

**Comment by stof** [comment]
Closing this issue as it is not an issue with the bundle.

and if you want help for that, you will need to provide a stack trace of the exception (run your CLI in verbose mode for that). Otherwise it is impossible to help you. I suggest you to ask on StackOverflow, which is the official support channel for Symfony.
