### ISSUE TITLE
fos:js-routing:dump cannot be use with Assetic

### ISSUE THREAD

**Issue by guillaumelecerf** [FriendsOfSymfony/FOSJsRoutingBundle#212]
The doc https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/blob/master/Resources/doc/index.md#fosjs-routingdump states that you can use Assetic to load `js/fos_js_routes.js` in your twig template, but there is a problem:

with an empty cache, if you run the `cache:clear` Symfony command, it will trigger the Assetic cache-warmer.  But, if your template uses the Assetic way to include `js/fos_js_routes.js`, an exception will be only be logged (and not thrown):
`assetic.ERROR: The template "xBundle:template.html.twig" contains an error: The source file "/var/web/js/fos_js_routes.js" does not exist.`
because this file does not yet exist.

I think that it must be removed from the docs, as it is **very** hard to debug!

Besides, I will contact the Assetic maintainer to see if he could not only log the error, but fail with an exception.

See #213

**Comment by rudzboy** [comment]
+1

**Comment by guillaumelecerf** [comment]
@willdurand : gentle ping

**Comment by willdurand** [comment]
Is Assetic still alive? :)

Honestly, I don't know how Assetic is supposed to work. It used to work like 3 or 4 years ago when I wrote this bundle and used it with Assetic but now... Maybe this does not work anymore :(
