### ISSUE TITLE
fos:js-routing:dump serve pure json

### ISSUE THREAD

**Issue by gseidel** [FriendsOfSymfony/FOSJsRoutingBundle#219]
To run fos js routing with require.js i use this function to get the routes in pure json

```
{{ path('fos_js_routing_js', {'_format': 'json', 'noext': 1}) }}
```

In prod i want to use the fos:js-routing:dump the create exact the same file, but it's not possible because i need to set a callback option. It would be great to have the possibility to get only json without any callback.

So i would implement something like:

```
fos:js-routing:dump --no-callback
```

Or:

```
fos:js-routing:dump --callback=null
```

I think the first solution is nicer

**Comment by tobias-93** [comment]
Fixed in #302
