### ISSUE TITLE
--locale option does not produce js route file with specified locale

### ISSUE THREAD

**Issue by slucas-nwx** [FriendsOfSymfony/FOSJsRoutingBundle#222]
I have tried a few methods to generate a locale specific file.

command line : php app/console fos:js-routing:dump --locale="en_US"
js include : {{ path('fos_js_routing_js', {'locale' : app.request.getLocale(),'callback': 'fos.Router.setData'}) }}"
--locale-only isn't supported at all.

I would appreciate some help if I'm using either method inncorectly. 

Thanks

**Comment by willdurand** [comment]
I guess you run version `1.x`, which does not provide such a feature, cf. https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/blob/1.x/Resources/doc/index.md

**Comment by slucas-nwx** [comment]
Just FYI, I ended up running this to generate the routes with the correct locales.

php app/console fos:js-routing:dump --locale "en_US__RG__" --target "web/js/fos/fos_js_routes_en_US.js" --process-isolation

So I could have a file for each locale we support and cache the generated file instead of generating on the fly.

~Sara

**Comment by willdurand** [comment]
Hi @slucas-nwx, thanks for the feedback. So is `--process-isolation` the "fix" for your problem?

**Comment by slucas-nwx** [comment]
Actually rendering the target file in our shell script we run ahead of time resolved it.
Trying to do it dynamically in the twig was causing most of the grief, since the user can switch locales with a dropdown.
