### ISSUE TITLE
symfony 3.0.1 support

### ISSUE THREAD

**Issue by pivolan** [FriendsOfSymfony/FOSJsRoutingBundle#232]
composer installation failed
    - don't install symfony/serializer v2.7.6|don't install symfony/symfony v3.0.1
    - don't install symfony/serializer v2.7.7|don't install symfony/symfony v3.0.1
    - don't install symfony/serializer v2.7.8|don't install symfony/symfony v3.0.1
    - don't install symfony/serializer v2.7.9|don't install symfony/symfony v3.0.1
    - don't install symfony/serializer v2.8.0|don't install symfony/symfony v3.0.1
    - don't install symfony/serializer v2.8.1|don't install symfony/symfony v3.0.1
    - don't install symfony/serializer v2.8.2|don't install symfony/symfony v3.0.1
    - Installation request for symfony/symfony 3.0.1.0 -> satisfiable by symfony/symfony[v3.0.1].
    - Installation request for friendsofsymfony/jsrouting-bundle ^1.5 -> satisfiable by friendsofsymfony/jsrouting-bundle[1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4].

**Comment by xabbuh** [comment]
see #196
