### ISSUE TITLE
How to generate DEV urls?

### ISSUE THREAD

**Issue by yceruto** [FriendsOfSymfony/FOSJsRoutingBundle#233]
All generated URLs (absolute or not) don't consider the development mode `/app_dev.php/` (base url)

Exists some way to configure that?

EDIT:
This is my code:
```twig
{% javascripts filter="?jsqueeze" output="js/app.js"
     'bundles/fosjsrouting/js/router.js'
     'js/fos_js_routes.js'
     ...
%}
     <script src="{{ asset_url }}"></script>
{% endjavascripts %}
```

**Comment by yceruto** [comment]
this problem not occurs when I use:
```twig
<script src="{{ path('fos_js_routing_js', {"callback": "fos.Router.setData"}) }}"></script>
```

**Comment by willdurand** [comment]
I think this is an issue with `{% javascripts ... %}`. Assetic maybe. I don't think it will get fixed easily.

**Comment by yceruto** [comment]
I solved this temporarily:
```html
<script type="text/javascript">
    Routing.setBaseUrl("{{ app.request.baseUrl }}")
</script>
```
The issue is related with `baseUrl` into `js/fos_js_routes.js`, it is static!

Thanks anyway.

**Comment by willdurand** [comment]
mmh, it should not be static :( The controller is supposed to send the base URL..

**Comment by stof** [comment]
@willdurand when dumping the file, the controller is not involved at all.
this is exactly why we wanted to refactor the logic in 2.x (not done yet though) to dump only routes in this file and load other settings from elsewhere (I suggested using ``<meta>`` tags in the head)

**Comment by willdurand** [comment]
@stof you're absolutely right, but I failed at delivering this feature. I am going to create a milestome (3.0.0) for this feature, but I will not be able to work on it right now..
