### ISSUE TITLE
[RFC] Publishing FOSJsRoutingBundle docs on symfony.com

### ISSUE THREAD

**Issue by javiereguiluz** [FriendsOfSymfony/FOSJsRoutingBundle#236]
In http://symfony.com/doc/bundles/ we're publishing the documentation of the most relevant Symfony bundles. FOSJsRoutingBundle is one of the few missing Top10 bundles. I'd like to transform your documentation from Markdown to RST format in order to integrate it on symfony.com.

Please, tell me if you agree with this before submitting a pull request. Thanks!

**Comment by stof** [comment]
Fine with me (please do the work in the 1.x branch)

**Comment by willdurand** [comment]
:+1:

**Comment by rvanlaarhoven** [comment]
Note that the `Read the documentation` link in the Readme is currently broken and should probably be fixed as soon as the documentation on Symfony.com is live.

**Comment by javiereguiluz** [comment]
Closing it as fixed by #237.
