### ISSUE TITLE
Cannot install v2.0-dev. Package not found error

### ISSUE THREAD

**Issue by prindacerk** [FriendsOfSymfony/FOSJsRoutingBundle#240]
I tried adding this into my Symfony 3 project (PHP v7.0). When I tried adding, I kept getting the error stating "The requested package friendsofsymfony/jsrouting-bundle could not be found in any version, there may be a typo in the package name.". However, if I go for an older version like v1.6, it works fine.

I want to use the latest version but I am forced to use an older version because of this. Can someone help me figure out what I should do to get this working?

**Comment by prindacerk** [comment]
If I install v2.0.0-alpha, it works too. But from the git version, 2.0-dev is the latest. So I want to use that.

**Comment by xabbuh** [comment]
How exactly did you try to install the bundle?

**Comment by prindacerk** [comment]
Through composer. I used PHPStorm's Composer window and added the bundle after selecting the version listed in the dropdown. I do the same for all the composer packages and it added fine.

**Comment by xabbuh** [comment]
Well, showing the exact version number you added and the minimum stability setting of your project would be helpful. Otherwise it's just guessing.

**Comment by prindacerk** [comment]
Hi Christian,

this is my composer.json file contents. See attached.

However, I did get the latest by changing '2.0-dev' to 'dev-master' and
then calling Composer Update. But this version is not working.

[image: Inline images 1]

**Comment by xabbuh** [comment]
It seems that something went wrong. But you can simply embed the contents of your `composer.json` file using the *Insert code* button above the text editor.

**Comment by prindacerk** [comment]
I have put the composer.json file in my google drive. Get it from there.

https://drive.google.com/file/d/0B0qm6DS5byMtVVI3ako0RXEzOW5reWdHVzc4VHpFYkN1cUxj/view?usp=sharing

**Comment by prindacerk** [comment]
https://drive.google.com/open?id=0B0qm6DS5byMtVVI3ako0RXEzOW5reWdHVzc4VHpFYkN1cUxj

**Comment by xabbuh** [comment]
@prindacerk Just replace `2.0-dev` with, for example, `2.0.x-dev` or `~2.0@dev`.

**Comment by prindacerk** [comment]
Problem is that with PHPStorm's Composer window, you can only select from the versions that have been published in composer (see attached image). Either I must add via command line (which is a hassle) or add an older version and change it in composer.json and then call update.

Anyway, I just wanted to keep you informed of this so you are aware of it.

![image](https://cloud.githubusercontent.com/assets/4536573/13812133/4ead18f0-eba0-11e5-871d-e90c3ee2e3b1.png)

**Comment by stof** [comment]
Well, this should be reported as a bug in the PhpStorm UI then. ``2.0-dev`` cannot be a branch version. It is ``2.0.x-dev``

**Comment by tobias-93** [comment]
Not an FOSJsRoutingBundle issue.
