### ISSUE TITLE
Where to place my routes

### ISSUE THREAD

**Issue by hermandinho** [FriendsOfSymfony/FOSJsRoutingBundle#242]
Do i have to always place my routes in app/routing.yml? because routes under my bundles are not accessible via Routing.generate('route_id') from my .js files.

Thanks in advance.

**Comment by stof** [comment]
This bundle does not care about where routes are defined, as it just lets FrameworkBundle handle the loading of routes for the router, and then reads the loaded RouteCollection.

However, you have to mark your routes as exposed (by default, they are not). There are several ways to do so:
- set the ``expose`` option on the route when defining it (not easy for third-party bundles, but possible for AppBundle)
- set the ``expose`` option when importing a routing resource to expose all imported routes (handy if you want to expose all routes of the bundle)
- configure the list of exposed routes in your config (this configuration accept regular expression, without the ``#`` delimiter of the regex as they get combined):

    ```yaml
    fos_js_routing:
        routes_to_expose: [ route_1, route_2, ... ]
    ```

**Comment by hermandinho** [comment]
ok going to try that. thanks

**Comment by hermandinho** [comment]
cool it works. cloosing issue and thanks.
