### ISSUE TITLE
Repository Issues

### ISSUE THREAD

**Issue by jeremylivingston** [FriendsOfSymfony/FOSJsRoutingBundle#247]
Did something change with the permissions of this repository? I'm attempting to do a fresh clone and receiving the following:

```
$ git clone git@github.com:FriendsOfSymfony/FOSJsRoutingBundle.git
Cloning into 'FOSJsRoutingBundle'...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by stefk** [comment]
Using the https protocol, I have:

```
Cloning into 'FOSJsRoutingBundle'...
fatal: unable to access 'https://github.com/FriendsOfSymfony/FOSJsRoutingBundle.git/': 
transfer closed with outstanding read data remaining
```

**Comment by AxioTouma** [comment]
Same issue :sob:

**Comment by lenybernard** [comment]
I don't know what is going on but I had to deploy an app so I tried to fork the repo and use mine in a temporary way and it does work.

So if you don't know how to do, fork the repo, get the new url and add something like this in the composer.json:

```
    "repositories": [
        {
            "type": "vcs",
            "url" : "https://github.com/lenybernard/FOSJsRoutingBundle.git"
        }
    ],
```
of course replace lenybernard by your username

**Comment by werg27** [comment]
Same issue here ...

**Comment by VEnis** [comment]
Same issue :(

**Comment by jeremylivingston** [comment]
FYI: The issue seems to be resolved now.

**Comment by willdurand** [comment]
GitHub issue?

I checked the audit log: nothing, I checked permissions: nothing, I checked repo settings: nothing.

**Comment by jeremylivingston** [comment]
Odd. I'll close it out. This seemed to be the only repository that I use that was impacted, but everything is working as expected now.
