### ISSUE TITLE
Error with FOSJsRoutingBundle and KnpSnappyBundle

### ISSUE THREAD

**Issue by JM-PFC** [FriendsOfSymfony/FOSJsRoutingBundle#253]
Hello, I'm using version 2.3 of Symfony and KnpSnappyBudle to generate templates Twig HTML to PDF. I had a problem adding images, but I saw that the solution online using the URL request is solved. 
Example: `src = "{{app.request.scheme ~ ': //' ~  app.request.httpHost ~ asset ('img / logo.png')}}"`

Now I have a problem that I can not solve. I am using FOSJsRoutingBundle to generate routes and the template that convert to pdf with KnpSnappyBundle I have the following:

`         <Script type = "text / javascript" src = "{{path ('fos_js_routing_js', {" callback ":" fos.Router.setData "})}}"> </ script>`

With this line to generate the pdf gives me the following error (the same mistake that gave me the images before using routes on request):

> The exit status code '1' says something went wrong:
>     stderr: "Loading pages (1/6)
>     [> ] 0%
>     [======> ] 10%
>     QSslSocket: cannot resolve SSLv3_client_method
>     QSslSocket: cannot resolve SSLv3_server_method
>     [=======> ] 13%
>     [==========> ] 18%
>     [==========================> ] 44%
>     [============================> ] 47%
>     [==============================> ] 50%
>     [==============================> ] 50%
>     [===========================================> ] 73%
>     [==============================================> ] 78%
>     [============================================================] 100%
>     Counting pages (2/6)
>     [============================================================] Object 1 of 1
>     Resolving links (4/6)
>     [============================================================] Object 1 of 1
>     Loading headers and footers (5/6)
>     Printing pages (6/6)
>     [> ] Preparing
>     [============================================================] Page 1 of 1
>     Done
>     Exit with code 1 due to network error: ContentNotFoundError
>     "stdout: ""
>     command: /opt/lampp/htdocs/Symfony/app/../vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64 --lowquality --page-size 'A4' --viewport-size '‘1024x768’' '/tmp/knp_snappy576ad837d24a82.40556276.html' '/tmp/knp_snappy576ad837d25009.94614572.pdf'.

Is there any way to change that to work? I'm starting on this, so I would appreciate your help.

**Comment by ste93cry** [comment]
I had the same problem a few months ago while working on a project, and it turned out that you must use absolute urls with [wkhtmltopdf](http://wkhtmltopdf.org) (which is the program used by KnpSnappy to render the PDFs). So, instead of using the `path` function that generates a relative URL try to use `url` function instead: see [here](https://symfony.com/doc/current/templating.html#linking-to-pages) for details

**Comment by prodevcon** [comment]
Error exists with absolute paths .... 
If I omit:
`<script src="{{ absolute_url(path('fos_js_routing_js', { callback: 'fos.Router.setData' })) }}"></script>`

[wkhtmltopdf](http://wkhtmltopdf.org/) is working

Anybody managed to fix the problem?
