### ISSUE TITLE
ConflictingHeadersException with routing?callback=fos.Router.setData 

### ISSUE THREAD

**Issue by AntoineLemaire** [FriendsOfSymfony/FOSJsRoutingBundle#255]
Since this [PR](https://github.com/symfony/symfony/pull/18688) was merged, something I got some errors from my clients:

    Class name: Symfony\Component\HttpFoundation\Exception\ConflictingHeadersException 
    Message: The request has both a trusted Forwarded header and a trusted Client IP header, conflicting with each other with regards to the originating IP addresses of the request. This is the result of a misconfiguration. You should either configure your proxy only to send one of these headers, or configure Symfony to distrust one of them. 
    Uri: https://mydomain.fr/js/routing?callback=fos.Router.setData 

Here are my client HTTP Headers for this request

    HTTP_FORWARDED	'for="41.79.192.38:5377"'
    HTTP_X_FORWARDED_FOR	'41.79.195.38, 185.27.179.25'

Do you know what is the problem?

**Comment by xabbuh** [comment]
Why do the IP addresses in your request's headers differ?
