### ISSUE TITLE
2.0 Release date

### ISSUE THREAD

**Issue by xocasdashdash** [FriendsOfSymfony/FOSJsRoutingBundle#262]
Hi!

Is there an ETA on the 2.0 release date? I need to only expose some routes on some pages, and I think that this kind of scoping is included in the 2.0 release branch, am i right?

**Comment by CoalaJoe** [comment]
We demand answers 😞

**Comment by tobias-93** [comment]
I have just released version 2.0, please let me know if you run into any issues.
