### ISSUE TITLE
[Feature request] Routes per bundle

### ISSUE THREAD

**Issue by promarcel** [FriendsOfSymfony/FOSJsRoutingBundle#269]
Hey community,

I'm not sure if there is already a request for my idea and I currently not know if it is possible to do that:

But ist there any way to load the `fos_js_routing_js` only for a specific bundle ... for example I've three bundles in my project, I need for all bundles the routes, but I want generate the routes per bundle ... eg: the users can only see the users routes and not the routes of my admin bundle?

Have anybody a solution? Thanks for your requests! :-)

**Comment by stof** [comment]
Routes are not grouped per bundles in Symfony. They are not even loaded by bundles, so even Symfony cannot provide this info during the loading process. So filtering routes by bundle does not make sense.
