### ISSUE TITLE
Symfony 3.x support

### ISSUE THREAD

**Issue by bobvandevijver** [FriendsOfSymfony/FOSJsRoutingBundle#272]
Currently, this bundle is lacking Sf3.x support, but it looks like it should be fixed by merging #254. 

However, that PR is already more than half a year old. Is this bundle still maintained, or should we switch to another implementation?

**Comment by GuilhemN** [comment]
https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/pull/254 is merged.
