### ISSUE TITLE
Routing.generate generates route with query string instead of parameter

### ISSUE THREAD

**Issue by cAstraea** [FriendsOfSymfony/FOSJsRoutingBundle#279]
In exactly the same conditions 

url: Routing.generate('user_delete', { id: userId }) generated the correct route 
/app_dev.php/userDelete/fd899744-0d88-11e7-a304-77f8745d742e	
_route	user_delete
_route_params	[id => fd89d704-0d88-11e7-a304-77f8745d742e]

for another entity on another route 
 Routing.generate('airport_delete', { id: airportId }), generated the wrong route 
/app_dev.php/airportDelete?id=fd983614-0d88-11e7-a304-77f8745d742e	
_route_params	[]
and the id is added as query string 
What am I missing? The routes are defined exactly the same way 

     * @Route("/userDelete/{id}", name="user_delete", options={"expose"=true})
     * @Route("/userDelete", name="users_delete", options={"expose"=true})
     * @param User $user
     * @param Request $request
     * @return Response
     * @Method("DELETE")
     * @Security("is_granted('ROLE_ADMIN')")
     */

  /**
     * @\Symfony\Component\Routing\Annotation\Route("/airportDelete/{id}", name="airport_delete", options={"expose"=true})
     * @Route("/airportDelete", name="airport_delete", options={"expose"=true})
     * @param Airport $airport
     * @param Request $request
     * @return Response
     * @Method("DELETE")
     * @Security("is_granted('ROLE_ADMIN')")
     */

**Comment by stof** [comment]
for anyone looking at this in the future, this is because there are 2 definitions of the ``airport_delete`` route, so the second one (without an id in the pattern) overwrite the first one.

**Comment by cAstraea** [comment]
Yes thanks :) My bad didn't spot it. The second one should have been named airports_delete where I'm passing an array of items for all to be bulk deleted.
