### ISSUE TITLE
http and https issue

### ISSUE THREAD

**Issue by arpitajadeja212** [FriendsOfSymfony/FOSJsRoutingBundle#280]
I have added following fos files in my main layout 

<script src="{{ asset('bundles/fosjsrouting/js/router.js') }}"></script>
<script src="{{ path('fos_js_routing_js', {'callback': 'fos.Router.setData'}) }}"></script>

on production our url is secure with https:// and ajax call giving following error

"Blocked loading mixed active content http://www.examle.url(it is example our dmain url)"

**Comment by tobias-93** [comment]
This will be fixed in #254, but that has been open for a long time with no attention from the developers at all...

**Comment by GuilhemN** [comment]
https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/pull/254 merged.
