### ISSUE TITLE
unknown://

### ISSUE THREAD

**Issue by kevinvergauwen** [FriendsOfSymfony/FOSJsRoutingBundle#289]
@tobias-93: When schemes array of route is empty route has been generated with unknown://

`if (goog.object.containsKey(route, "schemes") && this.getScheme() != route.schemes[0])`

There is no check if the array is empty.

Occured on Symfony 2.8

**Comment by willdurand** [comment]
Hi @kevinvergauwen, which version are you using?

**Comment by tobias-93** [comment]
@kevinvergauwen fixed in #288, please use version 1.6.2 of the bundle

**Comment by kevinvergauwen** [comment]
OK, thanks @willdurand and @tobias-93 ! I used 1.6.1 ;-)
