### ISSUE TITLE
Error with SF 3.3.10

### ISSUE THREAD

**Issue by AntoineTesson** [FriendsOfSymfony/FOSJsRoutingBundle#297]
Hi,
The version 1.6.3 dont works with the latest version of symfony 3.3.10

/routing?callback=fos.Router.setData   => error 500 i'm sorry but no logs on the prod.log just try it.

with 3.3.9 no problem, so i have retrograded.
Thank's !

**Comment by tobias-93** [comment]
I cannot reproduce this, and am using SF 3.3.10 myself. Could you include a little more information in order for us to reproduce this?

**Comment by AntoineTesson** [comment]
Ok i will try tomorrow

**Comment by AntoineTesson** [comment]
Fixed with SF 3.3.11 and 3.3.12
