### ISSUE TITLE
Conflict with FOS User Bundle Routing...

### ISSUE THREAD

**Issue by JoshConnerty** [FriendsOfSymfony/FOSJsRoutingBundle#298]
Odd thing...

I'm currently running Symfony 3.2 with:
        "friendsofsymfony/jsrouting-bundle": "^1.6",
        "friendsofsymfony/user-bundle": "~2.0",

running.

All was fine with the user bundle until I installed the routing bundle and now every time I login the login page redirects me to:
http://localhost/app_dev.php/js/routing?callback=fos.Router.setData

Which just dumps the router file of exposed routes.

I may just be doing something stupid but I can't see why it might be happening.

**Comment by stof** [comment]
Well, the security.yml generally comes with a firewall disabling security for some routes (and so would not register it for the redirection). Just make sure that the route loading your translations is matched by  this firewall (which should be the case when it starts with `/js`: https://github.com/symfony/symfony-standard/blob/8065d0e2526bf973e316d82336a5543103274e43/app/config/security.yml#L12-L14)

**Comment by JoshConnerty** [comment]
Amateur mistake
