### ISSUE TITLE
Deprecated since Symfony 3.3

### ISSUE THREAD

**Issue by xorgxx** [FriendsOfSymfony/FOSJsRoutingBundle#299]
Hi just find this when i extends my controller form ``` Controller to AbstractController``` 

SF 3.3.10, FosJsRouting 1.6.3 
```
Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be
supported in version 4.0. You should rename (or alias) the "fos_js_routing.serializer" service to
"Symfony\Component\Serializer\SerializerInterface" instead.
```

thank

**Comment by stof** [comment]
The `fos_js_routing.serializer` alias is an internal one. It is *not* meant to provide autowiring for the Symfony serializer.

If you want an autowirable serializer, enable the serializer integration in FrameworkBundle.

**Comment by althaus** [comment]
Sorry for issue creeping...

Is there any reason the deprecation warning can popup **without** using the serializer service anywhere?

**Comment by stof** [comment]
@althaus maybe you have an autowired service in your project which uses the SerializerInterface typehint. Be careful also about tird-party bundles which might mark their services as autowired (or even worse, a compiler pass which could turn on autowiring for all services even when their author did not do it)

**Comment by althaus** [comment]
@stof I just grepped through our code and the only usage of the SerializerInterface I've found is the service subscription in the AbstractController. Would this collide?

**Comment by stof** [comment]
hmm, it could be the the one triggering the loading of the BC layer.

Note that a way to get rid of this deprecation warning is to turn on strict autowiring (i.e. disabling the BC layer)

**Comment by althaus** [comment]
Yeah, we've got a quite hugh and modular app still based on 3.4 and we cannot activate the strict wiring yet.

We'll see what the future brings. Thanks for your feedback. 👍
