### ISSUE TITLE
Allow by pattern

### ISSUE THREAD

**Issue by beberlei** [FriendsOfSymfony/FOSJsRoutingBundle#3]
Just reading the README i would prefer to configure the allowed routes by a whitelist that allows patterns, so i can do stuff like allowing all routes starting with "mybundle_". So i would specify the allowed_routes as patterns and the bundle would use preg_match to look if a route is in or not.

Also a command to look which routes actually get exposed, "router:debug-exposed" or somtehing would be helpful to verify the routes exported to javascript.

**Comment by xDaizu** [comment]
This functionality (exposing patterns) should be mentioned in the [documentation](https://symfony.com/doc/master/bundles/FOSJsRoutingBundle/usage.html)
