### ISSUE TITLE
The service "fos_js_routing.dump_command" tagged "console.command" must be public

### ISSUE THREAD

**Issue by raniery** [FriendsOfSymfony/FOSJsRoutingBundle#306]
I got this error when I updated to 2.1.0. My symfony version is v2.8.32.

Updating friendsofsymfony/jsrouting-bundle (2.0.0 => 2.1.0): Downloading (100%)

[InvalidArgumentException]
  The service "fos_js_routing.dump_command" tagged "console.command" must be public.

**Comment by stof** [comment]
hmm, command services should not be marked as private explicitly, but use the default visibility (i.e. public on older versions of Symfony and private in 4.0).
This way, the commands will stay public on Symfony versions needing that.

**Comment by tobias-93** [comment]
I just released version 2.1.1, which should not contain this problem anymore. Thank you for reporting this issue!

**Comment by raniery** [comment]
Thanks!!!
