### ISSUE TITLE
no routes found

### ISSUE THREAD

**Issue by onokje** [FriendsOfSymfony/FOSJsRoutingBundle#309]
From some reason, the bundle cannot find the routes in my project.
My dumped json looks like this:
`{"base_url":"","routes":[],"prefix":"","host":"localhost","scheme":"http"}`

`bin/console fos:js-routing:debug` shows nu routes either.

but `./bin/console debug:router` shows many routes (including fos_js_routing_js).

I am using symfony 4. Any idea's?

**Comment by tobias-93** [comment]
Hi @onokje,

Did you add 
```
options:
  expose: true
```
to your routes, as described in https://symfony.com/doc/master/bundles/FOSJsRoutingBundle/usage.html ?

**Comment by onokje** [comment]
Ah yes, that did help :) I thought all routes were exposed by default. Thanks.
