### ISSUE TITLE
fos is not defined: (After updating from 2.1.0 to 2.2.0)

### ISSUE THREAD

**Issue by dani2819** [FriendsOfSymfony/FOSJsRoutingBundle#315]
I updated the version from 2.1.0 to 2.2.0, but now i am getting error that "fos is not defined".

I also want to add here that i have react application in which i included the files as:
```
require('../../web/bundles/fosjsrouting/js/router.js');
require('../../web/js/fos_js_routes.js');      
```   
It was working before perfectly, but after updating its not.

**Comment by tjveldhuizen** [comment]
What did you do to fix the issue? In my code, the same problem occured with version 2.2.0

**Comment by dani2819** [comment]
Actually for version 2.2.0, you have to make some modifications in routing setup. You have to following:
`import Routing from '../../web/bundles/fosjsrouting/js/router';`
`const routes = require('../../web/js/fos_js_routes.json');`
`Routing.setRoutingData(routes);`

Notice that, instead of 'fos_js_routes.js', you need to require its json file not js.
