### ISSUE TITLE
Typescript declaration is outdated

### ISSUE THREAD

**Issue by stof** [FriendsOfSymfony/FOSJsRoutingBundle#323]
Since the refactoring of #303, the typescript declaration is not uptodate anymore /cc @tristanlins

**Comment by laland** [comment]
Hi, @stof. I'we got rewritten js router into ts in my own repo https://github.com/laland/fos-js-router. I`ve ported  (i mean copy&pasted then tweaked a bit) all the stuff, including tests. There is now a webpack build process with bundling to es5-umd, with sourcemaps and d.ts. Please check out. 

It's initially made for my company's current projects, it works just like the original one, we gonna use it in production, and i'm ready to share it with community. What you think?

Bazinga translator already has its own npm-package, may be its time for fos-js-router to have one?

**Comment by stof** [comment]
Publishing it on NPM is something I would like to to, yes. Rewriting the full project to typescript is not something I'm planning though. We are using ES6 for the source now (and I don't want to maintain 2 codebases).

This issue is related to the typescript declaration file which was contributed by the community to provide types for TS users. When refactoring the code to expose it as a mode, we added some new APIs which are not in it.

**Comment by laland** [comment]
Ok, thanks for answer. May i publish my package to npm, maybe someone would like to use it? Should i port credits or something?

**Comment by stof** [comment]
I'd prefer if you don't name it `fos-js-router` if it is not the official FOS one. this would create confusion.

but anyway, what is the benefit of this port ? AFAIK, Typescript is totally able to consume NPM packages written in JS (and your own package would be JS code too on NPM as you compile it). If the benefit for users is the .d.ts file, I'd rather get contributions to the official one to update it (i.e. what this issue is about)

**Comment by laland** [comment]
Benefit is that declarations are completely inlined with the code, as they are generated from it. Specs are now covering not only the main functionality, but the singleton stuff too (and it's splitted out into it's own module, https://github.com/laland/fos-js-router/tree/master/src). All specs from original repo are still there. 

Tooling is upgraded to webpack and jasmine, which are pretty strong. And dist (https://github.com/laland/fos-js-router/tree/master/dist) is published in UMD which can be easily consumed, and all the sourcemaps and declarations are there. package.json has typings entry point as well. 

The story of this package is that, for example, i have some a symfony app, and frontend for this app has it's own repo - and there is no composer, no vendors folder, no php ), some all-js (all-ts to be shure) repo, that's need  router.js for some reason, but the only way to consume it is to install FosJsRoutingBundle, with composer, with php - but php does not fit into js project, so npm package is strongly needed.

> I'd prefer if you don't name it fos-js-router
Ok, it can be laland/js-router

By the way there is, for example https://www.npmjs.com/package/fos-routing npm-package, that failed in my build process for some reason. It has fos in its name.

And about credits, as of i copy-pasted most of code, what credits should i include? May i refer to this repo in my readme?

**Comment by laland** [comment]
Anyway, sorry for wasting your time )
Here's my package https://www.npmjs.com/package/symfony-ts-router

**Comment by Kocal** [comment]
Migrating the codebase to TypeScript would allow us to maintain both source code and types declaration files at the same time.

Actually, https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/blob/master/Resources/ts/router.d.ts is  really outdated and is hard to fix/maintain. 

Even the package from @laland can have types issues since it's desynchronized from this repository. I had to a PR for fixing a type (https://github.com/laland/symfony-ts-router/pull/4) and that's not ideal at all.

I'm sure that migrate to TypeScript will be beneficial to everyone. 

Since I will have a lot of free time the next days, I can give it a try. WDYT?

**Comment by tobias-93** [comment]
@Kocal that's a great idea, would be very nice if the code is migrated to TypeScript as that would make maintenance easier too. Thank you for the initiative, will gladly discuss any doubt you have and review the outcome.
