### ISSUE TITLE
Replace single colon with double in routing file

### ISSUE THREAD

**Issue by ReSpawN** [FriendsOfSymfony/FOSJsRoutingBundle#327]
For the upcoming release op 4.1 we're now getting a deprecation error because of routing.xml stating `fos_js_routing.controller:indexAction`, which sould be `fos_js_routing.controller::indexAction` (notice the double colon).

**Comment by stof** [comment]
See #325. Converting to the new notation would drop support for all older versions of Symfony where it does not work. Dropping support for 3.4 is not an option for now.

**Comment by DylanKruyff** [comment]
I'm also running into this issue. Our composer install triggers a nice visible deprecation error because of this.

@stof is using the `Kernel::VERSION_ID` an option to keep support for 3.4?

**Comment by stof** [comment]
well, this happens in an XML file, so detecting the version to use would actually be hard

**Comment by dspiegel** [comment]
Hi @stof 
I'm confused. 
Isn't it the purpose of GIT version tags and composer to pick the proper tagged versions based on requirements? 

If so, how could a change for Symfony 4..1 affect Symfony 3.4 if  FOSJsRoutingBundle requires Symfony "^4.1"? It shouldn't install on anything with less than 4.1 right?

Perhaps I don't understand composer and version enough.

**Comment by tobias-93** [comment]
@dspiegel We don't want to limit our user base to the people running the latest version if there's no functional reason to do so. Otherwise, we would have to maintain multiple versions when bugs are solved etc. which is a lot of work for such a non-blocking deprecation error. Once SF5 will be released and this bundle cannot be used with it we might consider moving on, but for now that's no discussion.

**Comment by stof** [comment]
@yannickl88 but as people are importing our XML files, we cannot simply replace them with PHP files. That would be a BC break as they would have to change their imports.

**Comment by jdaviaud** [comment]
Still no new idea for this deprecation problem ? as most of new apps are using SF4 / 4.1 should be good to have an updated version for these versions, getting the deprecation error on most dev pages / phpunit tests are boring ...

No way to get an old version of the bundle for old users and an updated one for recent ones ( nearly one year now that SF4.1 is out :'( )

**Comment by tristanbes** [comment]
True, a solution to fix those deprecation warning would help us clear our stacktrace on Sentry :D

**Comment by chucky2305** [comment]
Any updates on this? I do still get these deprecation messages
I am on symfony 4.2 and have 2.2.2 of jsRoutingBundle.

**Comment by tobias-93** [comment]
I have added an extra xml file, `routing-sf4.xml`. Use this file instead of `routing.xml` to fix the deprecation. Also see https://github.com/symfony/recipes-contrib/pull/610 for the new recipe, so new installs wil automatically use the new file.
