### ISSUE TITLE
Routing name has locale suffix

### ISSUE THREAD

**Issue by rjwebdev** [FriendsOfSymfony/FOSJsRoutingBundle#329]
I recently updated my Symfony application to 4.1 so I can use the new internationalized routing feature.

When I dump the exposed routes to a javascript file, 2 routes are generated, having the locale of the path as suffix. For example I have a route app.user.index with following paths:
- en: /users
- fr: /utilisateurs

In my generated file, I have to routes app.user.index.en and app.user.index.fr

**Comment by stof** [comment]
yeah, having 2 routes is how the Symfony 4.1 feature works internally (and Symfony tries to generate the locale-specific variant first).

the route generator in this bundle is not yet updated to support the same feature.

**Comment by rjwebdev** [comment]
Do you have any idea when this feature will be supported?

**Comment by stof** [comment]
The only answer I can give you is "when someone works on it". that's how open-source work when everyone is working on it on their free time (and I'm not using this bundle myself anymore since a long time, so it may not even be my priority on my free time)

**Comment by rjwebdev** [comment]
Is it possible to get some more info/input from someone who is still maintaining this bundle?

**Comment by rjwebdev** [comment]
@stof 

Any news on this issue so far?

**Comment by Padam87** [comment]
Probably the simplest safe way to work around this

```js
const locale = $('body').data('locale');
const RoutingDecorator = {
    generate: function (name, params) {
        const orig_name = name;
        try {
            Routing.getRoute(name)
        } catch(error) {
            name = name + '.' + locale;

            try {
                Routing.getRoute(name)
            } catch(error) {
                name = orig_name;
            }
        }

        return Routing.generate(name, params);
    }
};
```

**Comment by tobias-93** [comment]
This is now supported since #334 is merged.
