### ISSUE TITLE
Getting JavaScript error from routing script

### ISSUE THREAD

**Issue by Burgov** [FriendsOfSymfony/FOSJsRoutingBundle#34]
The bundle generates the following JS for me:

```
{"base_url":"","routes":{"department_day_budget":{"tokens":[["variable","\/","\\d{4}-\\d{2}-\\d{2}","date"],["text","\/budgeting"],["variable","\/","[^\/]+","id"],["text","\/department"],["variable","\/","[^\/]+","location_id"],["text","\/location"]],"defaults":[]}}}
```

for some reason both FF and Chrome complaint to me about this script:
FF: invalid label (with an arrow pointing at the very first ")
Chrome: Uncaught SyntaxError: Unexpected token :

any ideas?

**Comment by dmecke** [comment]
I had the same problem, in my case the reason was a mod_rewrite rule that matched all `/js` paths. This rule cut away the query parameter
