### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by marovargovcik** [FriendsOfSymfony/FOSJsRoutingBundle#342]
Hey,

It seems like this project is not published in npm registry. Would be really cool to have it.

What do you think?

Thanks.

**Comment by danrot** [comment]
I would also think so. As a solution in the mean time I've gone with a webpack alias like this:

```javascript
module.exports = (env, argv) => ({
    resolve: {
        alias: {
            'fos-jsrouting': path.resolve(
                rootPath,
                'vendor/friendsofsymfony/jsrouting-bundle/Resources/public/js'
            ),
        },
    },
});
```

**Comment by Magiczne** [comment]
@tobias-93 i see you're the main maintainer right now - maybe this could be addressed? As linking js package from composer vendor file is not a great solution

**Comment by Magiczne** [comment]
@marovargovcik you closed it cause the package was released? If so please link to it
