### ISSUE TITLE
Expose domains broken regex pattern

### ISSUE THREAD

**Issue by onEXHovia** [FriendsOfSymfony/FOSJsRoutingBundle#349]
After upgrading to version `2.3.0` not all route fall into the final list. With a quick check, the regular expression pattern gives out incorrect matches https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/blob/master/Extractor/ExposedRoutesExtractor.php#L90.

For example https://regex101.com/r/pYNG46/2 route `mh_user_social_render` must be fully matched and not partially. 

ping @tugrul @tobias-93

**Comment by tugrul** [comment]
I think this is ok by the example: https://regex101.com/r/pYNG46/3

**Comment by zerkms** [comment]
The v2.3.0 definitely breaks the `routes_to_expose`. One possible workaround is to use regular expressions and specify every exposed route name with beginning and end of string anchors, eg `^mh_user_social_render$`.

**Comment by aeyoll** [comment]
Hello. PR #350 is indeed fixing this issue. Can a maintainer review it and merge it if it's ok? Thanks a lot!

**Comment by tobias-93** [comment]
It is merged, sorry for the delay.

**Comment by aeyoll** [comment]
Thanks a lot @tobias-93! Can you do a new release on packagist? That would be great, thank you!

**Comment by tobias-93** [comment]
@aeyoll version 2.3.1 has just been released.
