### ISSUE TITLE
Expose domains not correct working

### ISSUE THREAD

**Issue by zdebol** [FriendsOfSymfony/FOSJsRoutingBundle#353]
Invalid argument list - not pass to constructor RoutesResponse $locale, so passed $domain is assign to $locale not to $domains variable

https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/blob/552c00c3e6302230f3cd444adfc4c58b4faea874/Command/DumpCommand.php#L182

**Comment by tobias-93** [comment]
Fixed in #334

**Comment by ruano-a** [comment]
@tobias-93 it doesn't seem to be.
I'm encountering issues while using the domains, because in RoutesResponse, $domain is set to $locale, and then $domains is empty. I'm using the version 2.6.

**Comment by ruano-a** [comment]
#398 fixing this issue
