### ISSUE TITLE
Generating absolute URL set host=localhost

### ISSUE THREAD

**Issue by florianajir** [FriendsOfSymfony/FOSJsRoutingBundle#357]
When I generate an url with absolute parameter = true from fosJsRoutingBundle the domain is not the good one; as classic symfony Router is able to produce.

eg:
```javascript
let myUrl = Router.generate('en__RG__look_view', {'slug': 'test'}, true);
console.log(myUrl); // http://localhost/en/look/view/test
//should produce: https://sub.domain.tld/en/look/view/test
```

```twig
{% set myUrl = url('look_view', {'slug': 'test'}) %}
{{ dump(myUrl) }} {# https://sub.domain.tld/en/look/view/test #}
```

Maybe I missed something in configuration ?

Note: My web server is php-fpm behind an nginx reverse proxy.

**Comment by stof** [comment]
how are you initializing the router ? With the controller or with a dumped file ?

**Comment by florianajir** [comment]
> how are you initializing the router ? With the controller or with a dumped file ?

with a dumped file generated on build time directly on the hosted server

**Comment by florianajir** [comment]
Problem solved I found the solution in the doc sorry I misread a part about configuring the router in command context (I tried previously but missed to the regenerate the file after)

https://symfony.com/doc/current/console/request_context.html#configuring-the-request-context-globally

**Comment by plamenh** [comment]
Any more specific hint about how to solve this? I have no idea how to fix the generate command.
