### ISSUE TITLE
Symfony 5.0 support

### ISSUE THREAD

**Issue by kl3sk** [FriendsOfSymfony/FOSJsRoutingBundle#365]
Hello,

This Bundle is so usefull, so I can't don't use it.
Symfony 5.0 is out now, does it planned to update/support ?

**Comment by stof** [comment]
There is already an open PR starting the work.

**Comment by kl3sk** [comment]
My bad sorry I didn't see it. I see [it](https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/pull/364) now. Hope merged soon.

Thx

**Comment by kl3sk** [comment]
@stof please consider https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/pull/366/commits/5dfca90c7dcd28a10def4ca25c34fe05179e01e4
