### ISSUE TITLE
Port number is duplicated on absolute path generation with non-standard ports

### ISSUE THREAD

**Issue by robertosanval** [FriendsOfSymfony/FOSJsRoutingBundle#379]
I've discovered a weird problem.

When I use non-standard ports on my local dev server the generated URLs duplicates the port.

This is the code:
```
url = Routing.generate('style_new', { 'id': id }, true);
console.log(url);
```

I get this URL:
`https://localhost:4443:4443/admin/style/new/5`

**Comment by pierre-H** [comment]
same problem

**Comment by YoannChabert** [comment]
Maybe its the same problem as #377 ?

Check the version of symfony/serializer (version 5.0.5 have issues for me)

**Comment by robertosanval** [comment]
Thanks @YoannChabert but I'm using symfony/serializer 4.4.0

**Comment by YoannChabert** [comment]
I don't know if that can help, but i tried again the version 5.0.5 and it works !
But I also deleted all the content of bundles/* in my Symfony Project. 
Have you tried this ? @robertosanval

**Comment by ViniTou** [comment]
If there is an option this bug was introduced here?
as I have same bug on serializer 5.0.5 and 5.0.4.
https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/pull/361/files
@YoannChabert 
@robertosanval

**Comment by wadjeroudi** [comment]
@ViniTou I think you're right about this PR, I had to downgrade to fos js routing bundle to ~2.4.0.

**Comment by robertosanval** [comment]
Thanks for the fix!
