### ISSUE TITLE
no configuration for symfony 5 

### ISSUE THREAD

**Issue by elliotalld** [FriendsOfSymfony/FOSJsRoutingBundle#402]
im working with symfony 5 project , i install FosJsRoutingBundle , but there is no steps to configure it in symfony 5 !

**Comment by MaruanBO** [comment]
In the next days i will explain how to do.

**Comment by tobias-93** [comment]
Hi @elliotalld, I have improved the documentation a bit in release 3.0, feel free to open another issue if you run into more problems.
