### ISSUE TITLE
Bump php version?

### ISSUE THREAD

**Issue by Chris53897** [FriendsOfSymfony/FOSJsRoutingBundle#415]
Hi. Is there any interest to bump php version to ^7.4|^8.0" as supported Versions. https://php.watch/versions
I could do the PR

**Comment by Cryde** [comment]
It already support PHP 8 https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/blob/master/composer.json#L19

**Comment by Chris53897** [comment]
My proposal is to drop support of php < 7.4

**Comment by stephanvierkant** [comment]
Good idea! We should drop support for EOL-versions ASAP.

**Comment by tobias-93** [comment]
Has been included in release 3.0, thanks
