### ISSUE TITLE
Error installing with symfony 5

### ISSUE THREAD

**Issue by raulcejas04** [FriendsOfSymfony/FOSJsRoutingBundle#422]
Hello friends,

I tried to install your bundle with "composer require friendsofsymfony/jsrouting-bundle"  in Symfony 5.3.12 and I got:

Problem 1
    - Root composer.json requires friendsofsymfony/jsrouting-bundle ^3.0 -> satisfiable by friendsofsymfony/jsrouting-bundle[3.0.0].
    - friendsofsymfony/jsrouting-bundle 3.0.0 requires symfony/framework-bundle ^5.4|^6.0 -> found symfony/framework-bundle[v5.4.0, v5.4.1, v6.0.0, v6.0.1] but it conflicts with your root composer.json require (5.3.*).

Thank you

**Comment by tobias-93** [comment]
Hi, thanks for your interest in our bundle. From version 3.x of our bundle we only support Symfony 5.4 (being the LTS) and higher, and PHP 8.0 and higher. If you cannot upgrade yet you can use version 2.x and upgrade once you're ready.
