### ISSUE TITLE
Bug - Routing.generate

### ISSUE THREAD

**Issue by BenjaminPoutriquet35800** [FriendsOfSymfony/FOSJsRoutingBundle#423]
Hi :)

I am having a problem when I try to generate one route from JS.

Explanation :

Controller definition :
![route_def_controller](https://user-images.githubusercontent.com/25900708/147332937-c39c77af-fff6-4ea1-96ff-7f356535c674.PNG)

Render route from twig : 
![render_twig](https://user-images.githubusercontent.com/25900708/147333165-af2a1307-7622-45bf-833c-dab8cd259074.PNG)

But from JS : 
![route_from_js](https://user-images.githubusercontent.com/25900708/147333194-cbe9f453-9794-4367-9da1-47b6777cd446.PNG)

Router does nothing :(

Regards

**Comment by BenjaminPoutriquet35800** [comment]
I think problem is this var : hasDefault in if condition
![image](https://user-images.githubusercontent.com/25900708/147336188-6bbe569b-1243-43cf-9b06-c9e9274d1b7e.png)

**Comment by tobias-93** [comment]
Hi @BenjaminPoutriquet35800, explicit inclusion of defaults using the exclamation mark was not supported yet in this bundle. I have added it in 22029dedd87e7ab9d82c585ea8c7aef63b37e21f, can you try if the `dev-master` branch works for you? Thanks

**Comment by BenjaminPoutriquet35800** [comment]
Hi @tobias-93 

Awesome that's good ! Really thanks <3

Regards

**Comment by tobias-93** [comment]
Version 3.1.0 has been released with the added functionality
