### ISSUE TITLE
Routing dump does not include port for local dev

### ISSUE THREAD

**Issue by lampelk** [FriendsOfSymfony/FOSJsRoutingBundle#440]
When dumping routes on local dev:

```shell
fos:js-routing:dump --format=json --target=public/js/routes.json
```

The json output does not include `port` if the web server is running with a port (e.g. `8080`):

```json
{
  "base_url": "",
  "routes": {
    "app_home": {
      "tokens": [["text", "\/home"]],
      "defaults": [],
      "requirements": [],
      "hosttokens": [],
      "methods": [],
      "schemes": []
    }
  },
  "prefix": "",
  "host": "localhost",
  "port": "",
  "scheme": "http",
  "locale": ""
}
```

**Expected result:**
```json
"port": 8080
```

I found this issue when trying  to generate absolute URLs:

```javascript
Routing.generate('app_home', /* your params */, true)
```

**Result:**
```
http://localhost/home
```

**Expected result:**
```
http://localhost:8080/home
```

**Environment:**
**php**: 8.0.2
**symfony**: 6.0*
**friendsofsymfony/jsrouting-bundle**: 3.1.1

Related (maybe?): #391

**Comment by bobvandevijver** [comment]
You can try setting the `HTTP_HOST` env var when generating the file to `localhost:8080`. Are you using the older `fos-routing` npm package, or the one bootstrapped with the bundle?
