### ISSUE TITLE
Symfony 6.3 deprecations when dump routes

### ISSUE THREAD

**Issue by tejashjimuliya** [FriendsOfSymfony/FOSJsRoutingBundle#461]
Getting following deprecation message in Symfony 6.3 when dump routes by following command

`$ bin/console fos:js-routing:dump --format=json --target=web/js/fos_js_routes.json`

`{"message":"User Deprecated: Method \"Symfony\\Component\\HttpKernel\\Bundle\\Bundle::build()\" might add \"void\" as a native return type declaration in the future. Do the same in child class \"Bazinga\\Bundle\\JsTranslationBundle\\BazingaJsTranslationBundle\" now to avoid errors or add an explicit @return annotation to suppress this message."`

**Comment by tobias-93** [comment]
Hi, thanks for opening an issue. However, as you can see in the notice, this is related to the BazingaJsTranslationBundle (https://github.com/willdurand/BazingaJsTranslationBundle) and not to this bundle. Our bundle.php file does not have this method, so it could not trigger this notice (see https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/blob/master/FOSJsRoutingBundle.php). You should contact the other bundle. Closing this here.
